#!/bin/bash
echo ""
echo "**********"
echo "start norminette test ex00"
norminette -R CheckForbiddenSourceHeader ../ex00/ft_print_alphabet.c
echo "end norminette test ex00"
echo "**********"
echo ""
echo "**********"
echo "start norminette test ex01"
norminette -R CheckForbiddenSourceHeader ../ex01/ft_print_reverse_alphabet.c
echo "end norminette test ex01"
echo "**********"
echo ""
echo "**********"
echo "start norminette test ex02"
norminette -R CheckForbiddenSourceHeader ../ex02/ft_print_numbers.c
echo "end norminette test ex02"
echo "**********"
echo ""
echo "**********"
echo "start norminette test ex03"
norminette -R CheckForbiddenSourceHeader ../ex03/ft_is_negative.c
echo "end norminette test ex03"
echo "**********"
echo ""
echo "**********"
echo "start norminette test ex04"
norminette -R CheckForbiddenSourceHeader ../ex04/ft_print_comb.c
echo "end norminette test ex04"
echo "**********"
echo ""
echo "**********"
echo "start norminette test ex05"
norminette -R CheckForbiddenSourceHeader ../ex05/ft_print_comb2.c
echo "end norminette test ex05"
echo "**********"
echo ""
echo "**********"
echo "start norminette test ex06"
norminette -R CheckForbiddenSourceHeader ../ex06/ft_putnbr.c
echo "end norminette test ex06"
echo "**********"
echo ""
echo "**********"
echo "start norminette test ex07"
norminette -R CheckForbiddenSourceHeader ../ex07/ft_print_combn.c
echo "end norminette test ex07"
echo "**********"
echo ""
